### ISSUE TITLE
Chat template hangs itself when using LightMod .jar on Windows 

### ISSUE THREAD

**Issue by NPException** [oakes/Lightmod#2]
I downloaded the Lightmod-1.0.1.jar file and ran it. Program starts up as expected,
using ~300Mb of RAM.
But when I created a project from the "chat" template and switched to its tab, LightMod is starting to use more and more RAM, roughly to the 2Gb mark. At that point the program became unresponsive and I had to kill it.

I started it again from the command line, and saw the following message being printed endlessly:

```
Exception in thread "JavaFX Application Thread" netscape.javascript.JSException: TypeError: undefined is not a function (evaluating 'd.endsWith("\n")')
        at com.sun.webkit.dom.JSObject.fwkMakeException(JSObject.java:137)
        at com.sun.webkit.dom.JSObject.callImpl(Native Method)
        at com.sun.webkit.dom.JSObject.call(JSObject.java:106)
        at sun.reflect.GeneratedMethodAccessor35.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at clojure.lang.Reflector.invokeMatchingMethod(Reflector.java:93)
        at clojure.lang.Reflector.invokeInstanceMethod(Reflector.java:28)
        at lightmod.app$append_BANG_.invokeStatic(app.clj:141)
        at lightmod.app$append_BANG_.invoke(app.clj:136)
        at lightmod.app$init_server_logs_BANG_$fn__15445$fn__15447$fn__15448$fn__15449.invoke(app.clj:181)
        at clojure.lang.AFn.run(AFn.java:22)
        at com.sun.javafx.application.PlatformImpl.lambda$null$173(PlatformImpl.java:295)
        at java.security.AccessController.doPrivileged(Native Method)
        at com.sun.javafx.application.PlatformImpl.lambda$runLater$174(PlatformImpl.java:294)
        at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
        at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
        at com.sun.glass.ui.win.WinApplication.lambda$null$148(WinApplication.java:191)
        at java.lang.Thread.run(Unknown Source)
```

[EDIT] Using the regular Windows .exe file works, but I'd prefer to use a way to use LightMod without the need to install it. (Ideally portable on a usb stick, with the .jar and a .bat and .sh file next to it.)

**Comment by oakes** [comment]
Interesting, if the exe works but the jar doesn't, then that suggests the difference may be in the version of Java being used. The exe is using [JDK 9](http://www.oracle.com/technetwork/java/javase/downloads/jdk9-downloads-3848520.html). If you have version 8, I'd suggest updating to see if that fixes it. I'll look into this issue more closely later, because I definitely would like it to work on 8 as well.

**Comment by oakes** [comment]
I just released 1.0.2 with a potential fix for the issue. Please try the jar version and let me know if it helps.

**Comment by NPException** [comment]
It works now, thanks a lot! 😃 

If you don't mind, I have two questions (probably) unrelated to the issue:

1. I see the following warning in the command line when I start LightMod:
`Could not open/create prefs root node Software\JavaSoft\Prefs at root 0x80000002. Windows RegCreateKeyEx(...) returned error code 5.`
Is this something you care about? Should I create an issue for it?

2. LightMod is using ~1.8 GB of memory when I open up the chat project. Is this expected memory usage?

**Comment by oakes** [comment]
Great! I'll close the issue then. Regarding the warning, that is OK -- I get the same warning when I run Nightcode on Windows. Regarding memory usage, do you know if it is increasing over time? Lightmod is definitely memory intense, because it's running so many things internally (including the CLJS compiler, all your server side code, etc), but if it is continually increasing over a long period of time then it could be a memory leak.

**Comment by NPException** [comment]
Thanks for the info. I have not used it over longer periods of time yet, but for the amounts of time I used it it always hovered around the 1.8 GB mark.
